// Product highlights on an event: which part of the line the item is about.
//
// Division is a fixed list and the only required part -- it is the cut the
// marketing calendar is actually read by. Category and SKU are free text on
// purpose: jettylife.com has no product feed to pick from, and a list typed
// here by hand would be stale within a season. The link is how a row points at
// the real thing, a category or product page on the site.
//
// One example image per row is NOT stored here. It is an ordinary attachment
// carrying this row's id in its `slot` column, so a new event's files can be
// uploaded once the event exists without a second write to patch ids back in.

import { DIVISION_KEYS } from './taxonomy.js';

export const MAX_PRODUCTS = 40;

// Generated by the browser before the event is saved, so an image can name the
// row it belongs to while neither of them exists yet. Narrow on purpose: it
// reaches an R2 object key by way of the slot column.
const ROW_ID_RE = /^[a-z0-9][a-z0-9-]{0,39}$/;

function text(v, max) {
  if (v == null) return '';
  return String(v).trim().slice(0, max);
}

// Returns { products, errors }. `products` is a JSON string ready to store, or
// null when the event has no highlights -- the same convention as every other
// multi-value column here.
export function normaliseProducts(raw) {
  const errors = [];
  if (raw == null || raw === '') return { products: null, errors };

  let list = raw;
  if (typeof raw === 'string') {
    try { list = JSON.parse(raw); } catch (e) {
      return { products: null, errors: ['Product highlights were not readable.'] };
    }
  }
  if (!Array.isArray(list)) return { products: null, errors: ['Product highlights must be a list.'] };
  if (list.length > MAX_PRODUCTS) {
    return { products: null, errors: ['At most ' + MAX_PRODUCTS + ' product highlights per event.'] };
  }

  const out = [];
  const seenIds = [];
  list.forEach((entry, i) => {
    const row = entry && typeof entry === 'object' ? entry : {};
    const at = 'Product highlight ' + (i + 1) + ': ';

    const division = text(row.division, 40);
    const category = text(row.category, 120);
    const sku = text(row.sku, 120);
    const url = text(row.url, 500);

    // A row the person started and abandoned is dropped rather than refused --
    // clicking Add and changing your mind should not block the save.
    if (!division && !category && !sku && !url) return;

    if (!DIVISION_KEYS.includes(division)) {
      errors.push(at + (division ? 'unknown division "' + division + '".' : 'pick a division.'));
      return;
    }
    if (url && !/^https?:\/\//i.test(url)) {
      errors.push(at + 'the link must start with http:// or https://.');
      return;
    }

    const id = text(row.id, 40).toLowerCase();
    if (!ROW_ID_RE.test(id)) { errors.push(at + 'bad row id.'); return; }
    if (seenIds.includes(id)) { errors.push(at + 'duplicate row id.'); return; }
    seenIds.push(id);

    out.push({ id, division, category, sku, url });
  });

  if (errors.length) return { products: null, errors };
  return { products: out.length ? JSON.stringify(out) : null, errors };
}

// Stored JSON back into a list, never throwing: a column that somehow holds
// something else should cost the event its highlights, not its page.
export function readProducts(stored) {
  if (!stored) return [];
  try {
    const list = JSON.parse(stored);
    return Array.isArray(list) ? list : [];
  } catch (e) {
    return [];
  }
}
